# Chapter 8: Chi-square tests

### Chi-Square Goodness of Fit Test

In [5]:
from scipy.stats import chisquare
  # Observed frequencies from last month's adoptions
observed_counts = [50, 20, 15, 15]  # Dogs, Cats, Rabbits, Other
  #Expected frequencies based on historical proportions (40%, 30%, 20%, 10%) out of 100
expected_counts = [40, 30, 20, 10]
  # Perform Chi-Square Goodness of Fit Test
chi_square_statistic, p_value = chisquare(f_obs=observed_counts, f_exp=expected_counts)
  # Output
print("Chi−Square Statistic:", chi_square_statistic)
print("P−value:", p_value)

Chi−Square Statistic: 9.583333333333334
P−value: 0.022461160919861143


### Chi-Square Test of Independence

In [6]:
import numpy as np
from scipy.stats import chi2_contingency

# Creating the contingency table
data = np.array([[30, 20],
                 [25, 25]])

# Perform Chi-Square Test of Independence
chi2_stat, p_value, dof, expected = chi2_contingency(data)

print("Chi-Square Statistic:", chi2_stat)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

Chi-Square Statistic: 0.6464646464646464
P-value: 0.4213795037428696
Degrees of Freedom: 1
Expected Frequencies:
 [[27.5 22.5]
 [27.5 22.5]]


### Chi-Square Test of Homogeneity

In [8]:
import numpy as np
from scipy.stats import chi2_contingency

# Creating the contingency table
data = np.array([[40, 50, 60],
                 [50, 40, 60],
                 [45, 45, 60]])

# Perform Chi-Square Test of Homogeneity
chi2_stat, p_value, dof, expected = chi2_contingency(data)

print("Chi-Square Statistic:", chi2_stat)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

Chi-Square Statistic: 2.2222222222222223
P-value: 0.694962974261134
Degrees of Freedom: 4
Expected Frequencies:
 [[45. 45. 60.]
 [45. 45. 60.]
 [45. 45. 60.]]
